# Generated by Django 2.2.10 on 2020-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('main_url', models.URLField()),
                ('encoding', models.CharField(choices=[('utf-8', 'Arabic'), ('utf-8', 'Catalan'), ('iso-8859-2', 'Czech'), ('iso-8859-1', 'Danish'), ('iso-8859-1', 'German'), ('us-ascii', 'English (USA)'), ('iso-8859-1', 'Spanish (Spain)'), ('iso-8859-15', 'Estonian'), ('iso-8859-15', 'Euskara'), ('iso-8859-1', 'Finnish'), ('iso-8859-1', 'French'), ('utf-8', 'Galician'), ('utf-8', 'Hebrew'), ('iso-8859-2', 'Croatian'), ('iso-8859-2', 'Hungarian'), ('iso-8859-15', 'Interlingua'), ('iso-8859-1', 'Italian'), ('euc-jp', 'Japanese'), ('euc-kr', 'Korean'), ('iso-8859-13', 'Lithuanian'), ('iso-8859-1', 'Dutch'), ('iso-8859-1', 'Norwegian'), ('iso-8859-2', 'Polish'), ('iso-8859-1', 'Portuguese'), ('iso-8859-1', 'Portuguese (Brazil)'), ('iso-8859-2', 'Romanian'), ('koi8-r', 'Russian'), ('utf-8', 'Slovak'), ('iso-8859-2', 'Slovenian'), ('utf-8', 'Serbian'), ('iso-8859-1', 'Swedish'), ('iso-8859-9', 'Turkish'), ('utf-8', 'Ukrainian'), ('utf-8', 'Vietnamese'), ('utf-8', 'Chinese (China)'), ('utf-8', 'Chinese (Taiwan)')], max_length=20)),
            ],
            options={
                'verbose_name': 'List-Installation',
                'verbose_name_plural': 'List-Installations',
            },
        ),
    ]
